//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PilotLookUp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PilotLookUp.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [ObjectSet] Все объекты null.
        /// </summary>
        public static string AllObjectsNull {
            get {
                return ResourceManager.GetString("AllObjectsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attr.
        /// </summary>
        public static string AttrToolTip {
            get {
                return ResourceManager.GetString("AttrToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка вычисления.
        /// </summary>
        public static string CalculationError {
            get {
                return ResourceManager.GetString("CalculationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать строку.
        /// </summary>
        public static string CopyLine {
            get {
                return ResourceManager.GetString("CopyLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать Name.
        /// </summary>
        public static string CopyName {
            get {
                return ResourceManager.GetString("CopyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать выделенное.
        /// </summary>
        public static string CopySelected {
            get {
                return ResourceManager.GetString("CopySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать Title.
        /// </summary>
        public static string CopyTitle {
            get {
                return ResourceManager.GetString("CopyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копировать Value.
        /// </summary>
        public static string CopyValue {
            get {
                return ResourceManager.GetString("CopyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя: {0}.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DisplayName : {0}.
        /// </summary>
        public static string DisplayNameFormat {
            get {
                return ResourceManager.GetString("DisplayNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при переходе к атрибутам: {0}.
        /// </summary>
        public static string ErrorCopyAttr {
            get {
                return ResourceManager.GetString("ErrorCopyAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при переходе к дереву задач: {0}.
        /// </summary>
        public static string ErrorCopyTaskTree {
            get {
                return ResourceManager.GetString("ErrorCopyTaskTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке данных из репозитория: {0}.
        /// </summary>
        public static string ErrorLoadingRepository {
            get {
                return ResourceManager.GetString("ErrorLoadingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обработке клика меню: {0}.
        /// </summary>
        public static string ErrorMenuClick {
            get {
                return ResourceManager.GetString("ErrorMenuClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при обновлении выбора: {0}.
        /// </summary>
        public static string ErrorSelectionUpdate {
            get {
                return ResourceManager.GetString("ErrorSelectionUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsInitialized.
        /// </summary>
        public static string GridColumnIsInitialized {
            get {
                return ResourceManager.GetString("GridColumnIsInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsObligatory.
        /// </summary>
        public static string GridColumnIsObligatory {
            get {
                return ResourceManager.GetString("GridColumnIsObligatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsService.
        /// </summary>
        public static string GridColumnIsService {
            get {
                return ResourceManager.GetString("GridColumnIsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsValid.
        /// </summary>
        public static string GridColumnIsValid {
            get {
                return ResourceManager.GetString("GridColumnIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string GridColumnName {
            get {
                return ResourceManager.GetString("GridColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string GridColumnTitle {
            get {
                return ResourceManager.GetString("GridColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string GridColumnType {
            get {
                return ResourceManager.GetString("GridColumnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value.
        /// </summary>
        public static string GridColumnValue {
            get {
                return ResourceManager.GetString("GridColumnValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id: {0}.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id : {0}.
        /// </summary>
        public static string IdFormat {
            get {
                return ResourceManager.GetString("IdFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информация.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на invalid.
        /// </summary>
        public static string InvalidName {
            get {
                return ResourceManager.GetString("InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LookDB.
        /// </summary>
        public static string LookDBToolTip {
            get {
                return ResourceManager.GetString("LookDBToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LookUpView.
        /// </summary>
        public static string LookUpViewToolTip {
            get {
                return ResourceManager.GetString("LookUpViewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LookDB.
        /// </summary>
        public static string MenuLookDB {
            get {
                return ResourceManager.GetString("MenuLookDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LookSelected.
        /// </summary>
        public static string MenuLookSelected {
            get {
                return ResourceManager.GetString("MenuLookSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PilotLookUp.
        /// </summary>
        public static string MenuPilotLookUp {
            get {
                return ResourceManager.GetString("MenuPilotLookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No objects.
        /// </summary>
        public static string NoObjects {
            get {
                return ResourceManager.GetString("NoObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упс, ничего не выбрано..
        /// </summary>
        public static string NothingSelected {
            get {
                return ResourceManager.GetString("NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на null.
        /// </summary>
        public static string NullName {
            get {
                return ResourceManager.GetString("NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите Id или GUID.
        /// </summary>
        public static string PromptEnterIdOrGuid {
            get {
                return ResourceManager.GetString("PromptEnterIdOrGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя или Id.
        /// </summary>
        public static string PromptEnterNameOrId {
            get {
                return ResourceManager.GetString("PromptEnterNameOrId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Репозиторий пуст или недоступен..
        /// </summary>
        public static string RepositoryEmpty {
            get {
                return ResourceManager.GetString("RepositoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Репозиторий.
        /// </summary>
        public static string RepositoryName {
            get {
                return ResourceManager.GetString("RepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отозванные задания.
        /// </summary>
        public static string RevokedTasks {
            get {
                return ResourceManager.GetString("RevokedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchToolTip {
            get {
                return ResourceManager.GetString("SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранный элемент Id:.
        /// </summary>
        public static string SelectedElementId {
            get {
                return ResourceManager.GetString("SelectedElementId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MainView должен создаваться в STA потоке.
        /// </summary>
        public static string StaThreadError {
            get {
                return ResourceManager.GetString("StaThreadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tasks.
        /// </summary>
        public static string TasksToolTip {
            get {
                return ResourceManager.GetString("TasksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PilotLookUp.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
